-- -- Neo-tree is a Neovim plugin to browse the file system
-- -- https://github.com/nvim-neo-tree/neo-tree.nvim

-- return {
--     'nvim-neo-tree/neo-tree.nvim',
--     version = '*',
--     dependencies = {
--         'nvim-lua/plenary.nvim',
--         'nvim-tree/nvim-web-devicons', -- not strictly required, but recommended
--         'MunifTanjim/nui.nvim',
--     },
--     cmd = 'Neotree',
--     keys = {
--         { '\\',   '<cmd>Neotree focus<CR>', desc = 'Focus NeoTree', silent = true },
--         { '\\\\', '<cmd>Neotree close<CR>', desc = 'Close NeoTree', silent = true },
--     },
--     init = function()
--         -- Auto open Neo-tree on startup
--         vim.api.nvim_create_autocmd("VimEnter", {
--             callback = function()
--                 require("neo-tree.command").execute({ action = "show" })
--             end,
--         })
--     end,
--     opts = {
--         sources = { "filesystem", "buffers", "git_status" },
--         open_files_do_not_replace_types = { "terminal", "Trouble", "trouble", "qf", "Outline" },
--         filesystem = {
--             bind_to_cwd = false,
--             follow_current_file = { enabled = true },
--             use_libuv_file_watcher = true,
--             filtered_items = {
--                 visible = true,
--                 hide_dotfiles = false,
--                 hide_gitignored = false,
--                 never_show = { '.git', '.cache' },
--             },
--         },
--         default_component_configs = {
--             indent = {
--                 with_expanders = true,
--                 expander_collapsed = "",
--                 expander_expanded = "",
--                 expander_highlight = "NeoTreeExpander",
--             },
--             git_status = {
--                 symbols = {
--                     unstaged = "󰄱",
--                     staged = "󰱒",
--                 },
--             },
--         },
--     },
-- }
